### ISSUE TITLE
Fatal error: Call to undefined function handle_error() in submission preprocessor

### ISSUE THREAD

**Issue by georGEO1989** [formtools/core#133] opened 2018-01-15 19:33 UTC
I am getting an undefined function error when trying to open the submission pre-processor module. This is version 1.1.4 for the module and 2.2.5 for formtools. Attached is the error
![pre](https://user-images.githubusercontent.com/1258384/34958713-0ec4a17e-fa01-11e7-9966-cfe35602dbed.JPG)

**Comment by benkeen** [comment] 2018-01-16 04:01
Hi @georGEO1989, curious! I don't recall this ever being an issue, but I confess it's been a long time since I've worked with FT2. Did you have the Submission Pre-Parser module set up? If not, you could uninstall it and download a fresh copy of 1.1.4 [https://github.com/formtools/module-submission_pre_parser/releases] and try again.

**Comment by georGEO1989** [comment] 2018-01-16 13:03
That doesn't really help as there is still an issue and I can't use anything passed version 1.1.4. I'm a little confused as I keep running into problems like this. Is the only stable version of formtools the latest alpha version?

**Comment by benkeen** [comment] 2018-01-16 14:52
No, the v3 alpha isn't stable yet. I'm working towards getting it into beta now - but yes, v3 is the only version I'm focusing on (limited time!). Form Tools 2 has been out in the wild for years so that's the stable version - the problem is it's gotten extremely out of date, so different error scenarios are arising that weren't issues before. Possibly that's what's happening here. 

What version of PHP are you running, by the way?

I'll take a look at this tonight after work and see if I can reproduce - or at least identify what would be causing this. Sorry for the fuss!

**Comment by georGEO1989** [comment] 2018-01-16 14:57
I'm running PHP 5.6.31.

It's all good. Most of the issues I'm having I've been able to get around. It's just this one module that would be incredibly useful to run custom PHP scripts every time a form is submitted. I need to be able to send these results to another server database. Other wise I have to schedule the scripts and I'm skeptical about that.

**Comment by benkeen** [comment] 2018-01-17 04:51
Hey @georGEO1989,

I installed FT2 + the Submission Pre-Parser module and interestingly didn't ran into a problem. I'm on PHP 5.6.30. The line it's complaining about is absolutely a bug: the `handle_error` method doesn't exist: it must be referencing a deleted function. However, it'll only ever get thrown if the query to get the list of data in the module fails, which is why it hasn't come up before.

Could you check to see if the `[prefix]module_submission_pre_parser_rules` table exists in your database? I'm wondering if maybe the installation script isn't properly installing the module tables. Also, check the PHP logs to see if there are any handy errors appearing in the logs. 

Ben

**Comment by georGEO1989** [comment] 2018-01-17 14:45
I am not seeing that table on the database after installing the module for the third time. When I look at the logs this is what I am seeing:

```
[16-Jan-2018 13:40:57 UTC] PHP Stack trace:

[16-Jan-2018 13:40:57 UTC] PHP   1. {main}() C:\wamp64\www\formtools\modules\module-submission_pre_parser-1.1.3\index.php:0

[16-Jan-2018 13:40:57 UTC] PHP   2. ssp_get_rules() C:\wamp64\www\formtools\modules\module-submission_pre_parser-1.1.3\index.php:18

[17-Jan-2018 14:42:13 UTC] PHP Fatal error:  Call to undefined function handle_error() in C:\wamp64\www\formtools\modules\module-submission_pre_parser-1.1.4\library.php on line 44

[17-Jan-2018 14:42:13 UTC] PHP Stack trace:

[17-Jan-2018 14:42:13 UTC] PHP   1. {main}() C:\wamp64\www\formtools\modules\module-submission_pre_parser-1.1.4\index.php:0

[17-Jan-2018 14:42:13 UTC] PHP   2. ssp_get_rules() C:\wamp64\www\formtools\modules\module-submission_pre_parser-1.1.4\index.php:18
```

**Comment by benkeen** [comment] 2018-01-17 14:53
So yeah the installation script isn't running on the module. How odd... 

Just one hunch: is the folder named `submission_pre_parser`? If not, rename it to that and try a fresh install. It's not at all clear since I moved to github, but all modules need to have their `module-` prefix removed.

**Comment by georGEO1989** [comment] 2018-01-17 15:00
That actually seems to have cleared the issue. I was able to go into the module without it throwing PHP errors.

**Comment by georGEO1989** [comment] 2018-01-17 16:48
Not to keep asking for stuff but can you point me in the direction of examples for sending the form data to another server?

**Comment by benkeen** [comment] 2018-01-17 16:48
Drat, I do apologize! It's not at all obvious. Glad it's working now though.

I've update the module installation documentation locally and I'll update it online tonight. I'll also churn through each of the repo's main README's to include links to the installation page just to help others that run into this.

**Comment by benkeen** [comment] 2018-01-17 16:51
Regarding sending the data to another server there actually isn't anything specific for that... 

Depending on what data format you need and how fine-tuned you need it, I'd either look at the Export Manager module: https://docs.formtools.org/modules/export_manager/ to generate the data in the first place, or just do a simple MySQL dump. They'd both generate files. 

At that point, sending the data elsewhere is kind of out of scope for the project - you'd need to look at a separate script for automation, I think.

**Closed** 2018-01-21 05:29 UTC
