### ISSUE TITLE
Upgrade 3.0.7 -> 3.0.8 - Can't View form Submissions

### ISSUE THREAD

**Issue by ocbroadband** [formtools/core#327] opened 2018-09-24 22:28 UTC
Just upgraded from v3.0.7 -> 3.0.8.  I am unable to view my form submissions now by either clicking on 'View' from the form's page, or if after going to the edit mode for a specific form, attempting to click the 'View Submissions' icon at the top right.   Attempted to re-upload the files a couple times to insure nothing was missed, but same result.

PHP 7.2.7
FT v3.0.8

**Comment by ocbroadband** [comment] 2018-09-25 18:05
Anyone have any thoughts on this?  This is a show stopper.

**Comment by benkeen** [comment] 2018-09-26 03:01
Hey @ocbroadband, 

Hmm... that's mighty odd. 3.0.8 is really nothing to do with that - it was just a security update related to installations.

What happens when you click into the form? You get a blank page or get redirected somewhere? Is this a client account or an admin account you're using?

**Comment by benkeen** [comment] 2018-09-26 03:02
If you're totally stumped & this is really inconvenient - and don't mind me taking a look - feel free to email me at ben.keen@gmail.com with some temp login info and I'll take a look.

**Comment by ocbroadband** [comment] 2018-09-26 03:08
Sent.

**Comment by benkeen** [comment] 2018-09-27 15:20
Turns out the problem was that the Smarty template for that particular page had gotten corrupted and was outputting a blank page. I'm not sure of the cause of this - and to my knowledge this is the first time this has come up. Fixing it was just a matter of clearing out all the temp files in the `themes/[themes]/cache` folder. 

Glad it's fixed at least! Closing.

**Closed by benkeen** 2018-09-27 15:20 UTC
